"""Added file path

Revision ID: 0e26564a1041
Revises: f0709f7bfa1b
Create Date: 2025-05-12 10:35:05.793510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e26564a1041'
down_revision: Union[str, None] = 'f0709f7bfa1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('file_path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'file_path')
    # ### end Alembic commands ###
