"""create photos table

Revision ID: 117c6c568e67
Revises: 0dda5f8645bb
Create Date: 2025-05-09 10:26:11.752363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '117c6c568e67'
down_revision: Union[str, None] = '0dda5f8645bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('average_rating', sa.Integer(), nullable=True))
    op.drop_constraint('photos_owner_id_fkey', 'photos', type_='foreignkey')
    op.create_foreign_key(None, 'photos', 'users', ['owner_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('photos', 'rating')
    op.drop_column('photos', 'likes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('photos', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.create_foreign_key('photos_owner_id_fkey', 'photos', 'users', ['owner_id'], ['user_id'])
    op.drop_column('photos', 'average_rating')
    # ### end Alembic commands ###
