"""Added expiry date to models

Revision ID: 7cc9b79df0d5
Revises: 7ea6ff6f16e0
Create Date: 2025-05-16 14:25:02.348565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc9b79df0d5'
down_revision: Union[str, None] = '7ea6ff6f16e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('share_photos', sa.Column('shared_at', sa.DateTime(), nullable=True))
    op.add_column('share_photos', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('share_photos', 'expires_at')
    op.drop_column('share_photos', 'shared_at')
    # ### end Alembic commands ###
