"""update rating table

Revision ID: d873df55bd33
Revises: 117c6c568e67
Create Date: 2025-05-09 10:30:05.741247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd873df55bd33'
down_revision: Union[str, None] = '117c6c568e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('photo_id', sa.Integer(), nullable=True))
    op.add_column('ratings', sa.Column('photographer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ratings', 'users', ['photographer_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ratings', 'photos', ['photo_id'], ['photo_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_column('ratings', 'photographer_id')
    op.drop_column('ratings', 'photo_id')
    # ### end Alembic commands ###
