"""empty message

Revision ID: f0709f7bfa1b
Revises: d873df55bd33
Create Date: 2025-05-09 10:39:21.834868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0709f7bfa1b'
down_revision: Union[str, None] = 'd873df55bd33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_unique_constraint('unique_photo_rating', 'ratings', ['user_id', 'photo_id'])
    op.create_unique_constraint('unique_photographer_rating', 'ratings', ['user_id', 'photographer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_photographer_rating', 'ratings', type_='unique')
    op.drop_constraint('unique_photo_rating', 'ratings', type_='unique')
    op.drop_column('ratings', 'id')
    # ### end Alembic commands ###
